spring:
  # 配置测试和线上文件
  #profiles:
    #active: dev
  # 配置发送邮箱信息
  mail:
    host: smtp.qq.com
    username: ## 发件人邮箱
    password: ## 邮箱授权码或密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            trust: smtp.exmail.qq.com
          auth: true
          starttls:
            enable: true
            required: true
  # 解决一个tomcat多个项目问题
  jmx:
    enabled: false


#1、独立微服务
#2、异常处理
#3、定时重试邮件
#4、异步发送